export const FETCH_REACT_COMPONENT = 'FETCH_REACT_COMPONENT'
export const FETCH_INPUT_REACT_COMPONENT = 'FETCH_INPUT_REACT_COMPONENT'
export const FETCH_CLICKED_REACT_COMPONENT = 'FETCH_CLICKED_REACT_COMPONENT'

